### PR TITLE
update search URLs to use location protocol

### PR DESCRIPTION
**Pull request by carylwyatt**
When working on Advanced Search locally, the search part doesn't actually work thanks to the hard-coded `https` protocol. This update adds a check for the current `location.protocol`, then builds the search URL using `https` if that's the current protocol, otherwise falls back to `http`.

This is up on `dev-3` and looks like it's working. 

- [dev 3 `ls` advanced search](https://dev-3.babel.hathitrust.org/cgi/ls?a=page&page=advanced)
- [dev 3 `catalog` advanced search](https://dev-3.catalog.hathitrust.org/Search/Advanced)

But I'm interested to see if anyone can get my changes working locally with my new babel-local-dev firebird workflow.

Perhaps:
1. in `/babel/firebird-common`, `git fetch` and switch to the `TTO-166` branch
2. `docker compose run node bash` will drop you into a `I have no name!` exec where you can run npm commands
3. `cd /htapps/babel/firebird-common` 
4. `npm run babel` will build your files (and the asset manifest) and watch them for changes you make

if you got an error about missing a file or a package, you might need to `npm i` for good measure (I had this problem today)

I'm interested to see if this works for other people like I think it should. I'm also 100% sure there is a better way to run commands in docker than what I've done here, but it works!

And if you get my changes working locally, hopefully you can do an advanced search 🤞

### CODE REVIEW

**Comment by liseli** [comment]
@carylwyatt I have tested your PR locally and appear the issue `Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/htapps/babel/firebird-common/node_modules/kleur/colors.mjs' imported from /htapps/babel/firebird-common/node_modules/@sveltejs/vite-plugin-svelte/src/utils/log.js`. I have applied the following steps to fix the issue, but without success

1. npm i
2. npm audit fix
3. npm install -g npm@10.3.0 # the output of `npm run babel` showed me a message to upgrade npm version

Do you have some idea how to fix it?

**Comment by carylwyatt** [comment]
@liseli With `npm audit fix` you updated some packages, which will have changed the `package.json`, so I'm not sure how this will work, but this _could_ be a caching problem. Usually when I have issues with "module not found" even after I install, I try this:
-  `rm -rf node_modules` 
-  `rm -f pacakge-lock.json`
- `npm cache clean --force`
- `npm install`

But it will install the dependencies from your post-audit-fix updated `package.json`... which maybe isn't bad, but I haven't tested that.

**Review by moseshll — APPROVED** [review]
This worked perfectly for me.

**Review by liseli — APPROVED** [review]
I've tested it locally using a temporary cache `npm install --cache /tmp/empty-cache` and it is working

**Pull request merged**
