### PR TITLE
DEV-678 - general accordion support

### PR DESCRIPTION
**Pull request by respinos**
Port `details` behavior from `pt/2021`:

* animate open/close
* coordinate open/closing of `<details>` when the container as `data-role="accordion"]`

### CODE REVIEW

**Comment by respinos** [comment]
@carylwyatt the `scrollIntoView` shenanigans maybe should be an explicit option: it's useful in the `pt` sidebar where the accordions have a lot of content.

**Comment by carylwyatt** [comment]
I might need a screenshare walk-through on this one... I'm definitely confused. I'm sure it has to do with page turner functionality and meshing that with our new stuff, but why recreate accordions when bootstrap has accordions/collapse??

**Comment by respinos** [comment]
It's to use `<details>` intead of Bootstrap's `<div>` structure. It was a shoelace `sl-details` that worked with IE11 (much simpler HTML than managing all the identifiers in bootstrap's syntax).

🤔 OTOH, if we decide that's not important, Bootstrap Accordions can handle being resized, which is half of what this code does: https://codepen.io/respinos/pen/abRbzgd?editors=1010

**Review by carylwyatt — COMMENTED** [review]
Did this end up in [PR 9/DEV-679](https://github.com/hathitrust/firebird-common/pull/9)? Or is there still something here I need to review?

**Comment by respinos** [comment]
@carylwyatt nope --- I closed the ticket as WONTFIX but should have closed the PR.

**Pull request closed without merging**
